### ISSUE TITLE
Pingable role + auto-assignable role 

### ISSUE THREAD

**Issue by ArsenicApple** [1anakin20/ComputerSquadBot#29]
1. Make the bot assign a new role when a user uses a specific reaction on discord. 
Ex: The bot assigns the role `@ping-me` to a user whenever they react to a message made by the bot with`:blue_heart:`

2. Perhaps the command should be determined by specifying each role name and reaction name, separated by a colon?
Ex: `++autoassignrole ping-me:blue_heart among-us:brown_heart`
The bot then deletes the command message and then creates a message of its own, informing the user which reaction should be used.

3. Use the aforementioned feature to replace `@everybody` in the class alarm with a specific auto-assignable role.

**Comment by 1anakin20** [comment]
Closing the issue because I am taking the bot in a new direction. 
I will simplify the bot to be only an alarm bot. 
This could be a nice feature for a separate one.
