### ISSUE TITLE
Refactor configuration file

### ISSUE THREAD

**Issue by 1anakin20** [1anakin20/ComputerSquadBot#39]
At the moment the configuration file is read in the main method. It's getting messy to add more options.
It would be great to use a proper way of reading from the file in a key, value way. 
It should be done using a `.properties` file.

**Comment by frosse** [comment]
Hello! I would like to do this!

**Comment by 1anakin20** [comment]
Hello, I will assign you to it! Feel free to ask me for any help you need.
