### ISSUE TITLE
Create alarms file automatically

### ISSUE THREAD

**Issue by 1anakin20** [1anakin20/ComputerSquadBot#42]
If the alarms.json files doesn't exist it will throw an exception at the startup. If it doesn't exist it should be created automatically.

**Comment by kylejosterman** [comment]
What should the the default values for the BOT Token, Owner ID, and channel be? Or is there a way a user can input these then have it populate a .json file? I should be able to knock this out once I get that.

**Comment by 1anakin20** [comment]
The alarms.json doesn't have anything to do with the configuration file.
The alarm.json role is to save the alarms to persist them between restarts.

**Comment by frosse** [comment]
If you want I can this one.

**Comment by 1anakin20** [comment]
Perfect, you will be assigned.
