### ISSUE TITLE
change the "new" command to "add" command

### ISSUE THREAD

**Issue by TinyMemeLord** [1anakin20/ComputerSquadBot#52]
Using the "new" argument in the ++alarm command is kinda confusing. The "remove" argument is used to remove alarms so it makes sense to change the new argument to be "add". "add" is the opposite of "remove" so people won't get confused with the argument.

**Comment by Tegridy** [comment]
Hi, could you assign me please ?

**Comment by 1anakin20** [comment]
Yes
