### ISSUE TITLE
Code block autocomplete 

### ISSUE THREAD

**Issue by DuReaLDuCK** [1anakin20/ComputerSquadBot#54]
command: "++code *language* *paste code*"

All code pasted as text and transform it in a discord code block so like it the bot will take everything after the space following the ++code and will basically just do charactersForStartCodeblock + nameOfLanguageInLowerCase + newLineCharacter + stringOfCodeWhichIsTheArgument +  charactersForEndCodeblock  and print it in discord and of course delete the message of the command.

**Comment by 1anakin20** [comment]
Closed due to not being necessary anymore.
